---
io-services:
  reader:
    #    class: org.jlab.ersap.actor.pet.engine.SimPetStreamSourceEngine
    class: org.jlab.ersap.actor.pet.engine.SimPetMultiStreamSourceEngine
    name: Source
  writer:
    class: org.jlab.ersap.actor.pet.engine.PetStreamSinkEngine
    name: Sink
services:
  - class: org.jlab.ersap.actor.pet.engine.PetGeometryProcessorEngine
    name: GProcessor
configuration:
  io-services:
    reader:
      ringBufferSize: 1024
      dataSize: 100
      streamCount: 2
    #      streamHost: "hostname/IP"
    #      streamPort: 7777
    #      connectionTimeout: 5000
    #      readTimeout: 2000
    writer:
  services:
    GProcessor:
mime-types:
  - binary/data-evio
  - binary/data-jobj
