#!/usr/bin/env bash

#
# Copyright (c) 2021.  Jefferson Science Associates, LLC.
# Subject to the terms in the LICENSE file found in the top-level directory.
# Author gyurjyan
#

try_perl() {
    perl -MPOSIX -e ';' 1>/dev/null 2>&1
}

if ! try_perl; then
    set -m
fi

trap '' INT
trap 'kill -TERM $proc_pid' TERM

if try_perl; then
    perl -MPOSIX -e 'setpgid 0,0; exec @ARGV' "${@:2}" 2>&1 | tee "$1" &
    pipe_pid=$!
else
    "${@:2}" 2>&1 | tee "$1" &
    pipe_pid=$!
fi

proc_pid=$(jobs -p)

wait $pipe_pid
trap - TERM
wait $pipe_pid
