// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf C++ Version: 6.31.1

#ifndef data_2eproto_2epb_2eh
#define data_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_data_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_data_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_data_2eproto;
}  // extern "C"
namespace xmsg {
namespace proto {
enum Data_Type : int;
extern const uint32_t Data_Type_internal_data_[];
class Data;
struct DataDefaultTypeInternal;
extern DataDefaultTypeInternal _Data_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Data_class_data_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Payload_class_data_;
class Payload_Item;
struct Payload_ItemDefaultTypeInternal;
extern Payload_ItemDefaultTypeInternal _Payload_Item_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Payload_Item_class_data_;
}  // namespace proto
}  // namespace xmsg
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::xmsg::proto::Data_Type_internal_data_>
    internal::EnumTraitsImpl::value<::xmsg::proto::Data_Type>;
}  // namespace protobuf
}  // namespace google

namespace xmsg {
namespace proto {
enum Data_Type : int {
  Data_Type_T_VLSINT32 = 1,
  Data_Type_T_VLSINT64 = 2,
  Data_Type_T_FLSINT32 = 3,
  Data_Type_T_FLSINT64 = 4,
  Data_Type_T_FLOAT = 5,
  Data_Type_T_DOUBLE = 6,
  Data_Type_T_STRING = 7,
  Data_Type_T_BYTES = 8,
  Data_Type_T_VLSINT32A = 9,
  Data_Type_T_VLSINT64A = 10,
  Data_Type_T_FLSINT32A = 11,
  Data_Type_T_FLSINT64A = 12,
  Data_Type_T_FLOATA = 13,
  Data_Type_T_DOUBLEA = 14,
  Data_Type_T_STRINGA = 15,
  Data_Type_T_BYTESA = 16,
  Data_Type_T_PAYLOAD = 17,
};

extern const uint32_t Data_Type_internal_data_[];
inline constexpr Data_Type Data_Type_Type_MIN =
    static_cast<Data_Type>(1);
inline constexpr Data_Type Data_Type_Type_MAX =
    static_cast<Data_Type>(17);
inline bool Data_Type_IsValid(int value) {
  return 1 <= value && value <= 17;
}
inline constexpr int Data_Type_Type_ARRAYSIZE = 17 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Data_Type_descriptor();
template <typename T>
const ::std::string& Data_Type_Name(T value) {
  static_assert(::std::is_same<T, Data_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return Data_Type_Name(static_cast<Data_Type>(value));
}
template <>
inline const ::std::string& Data_Type_Name(Data_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Data_Type_descriptor, 1, 17>(
      static_cast<int>(value));
}
inline bool Data_Type_Parse(
    ::absl::string_view name, Data_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Data_Type>(Data_Type_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Data final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:xmsg.proto.Data) */ {
 public:
  inline Data() : Data(nullptr) {}
  ~Data() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Data* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Data));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Data(::google::protobuf::internal::ConstantInitialized);

  inline Data(const Data& from) : Data(nullptr, from) {}
  inline Data(Data&& from) noexcept
      : Data(nullptr, ::std::move(from)) {}
  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }
  inline Data& operator=(Data&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Data& default_instance() {
    return *reinterpret_cast<const Data*>(
        &_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Data& a, Data& b) { a.Swap(&b); }
  inline void Swap(Data* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Data* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Data* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Data>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Data& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Data& from) { Data::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Data* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "xmsg.proto.Data"; }

 protected:
  explicit Data(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Data(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Data& from);
  Data(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Data&& from) noexcept
      : Data(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = Data_Type;
  static constexpr Type T_VLSINT32 = Data_Type_T_VLSINT32;
  static constexpr Type T_VLSINT64 = Data_Type_T_VLSINT64;
  static constexpr Type T_FLSINT32 = Data_Type_T_FLSINT32;
  static constexpr Type T_FLSINT64 = Data_Type_T_FLSINT64;
  static constexpr Type T_FLOAT = Data_Type_T_FLOAT;
  static constexpr Type T_DOUBLE = Data_Type_T_DOUBLE;
  static constexpr Type T_STRING = Data_Type_T_STRING;
  static constexpr Type T_BYTES = Data_Type_T_BYTES;
  static constexpr Type T_VLSINT32A = Data_Type_T_VLSINT32A;
  static constexpr Type T_VLSINT64A = Data_Type_T_VLSINT64A;
  static constexpr Type T_FLSINT32A = Data_Type_T_FLSINT32A;
  static constexpr Type T_FLSINT64A = Data_Type_T_FLSINT64A;
  static constexpr Type T_FLOATA = Data_Type_T_FLOATA;
  static constexpr Type T_DOUBLEA = Data_Type_T_DOUBLEA;
  static constexpr Type T_STRINGA = Data_Type_T_STRINGA;
  static constexpr Type T_BYTESA = Data_Type_T_BYTESA;
  static constexpr Type T_PAYLOAD = Data_Type_T_PAYLOAD;
  static inline bool Type_IsValid(int value) {
    return Data_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = Data_Type_Type_MIN;
  static constexpr Type Type_MAX = Data_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = Data_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Type_descriptor() {
    return Data_Type_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Type_Name(T value) {
    return Data_Type_Name(value);
  }
  static inline bool Type_Parse(
      ::absl::string_view name, Type* PROTOBUF_NONNULL value) {
    return Data_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kVLSINT32AFieldNumber = 9,
    kVLSINT64AFieldNumber = 10,
    kFLSINT32AFieldNumber = 11,
    kFLSINT64AFieldNumber = 12,
    kFLOATAFieldNumber = 13,
    kDOUBLEAFieldNumber = 14,
    kSTRINGAFieldNumber = 15,
    kBYTESAFieldNumber = 16,
    kSTRINGFieldNumber = 7,
    kBYTESFieldNumber = 8,
    kVLSINT64FieldNumber = 2,
    kVLSINT32FieldNumber = 1,
    kFLSINT32FieldNumber = 3,
    kFLSINT64FieldNumber = 4,
    kDOUBLEFieldNumber = 6,
    kFLOATFieldNumber = 5,
    kTypeFieldNumber = 17,
  };
  // repeated sint32 VLSINT32A = 9;
  int vlsint32a_size() const;
  private:
  int _internal_vlsint32a_size() const;

  public:
  void clear_vlsint32a() ;
  ::int32_t vlsint32a(int index) const;
  void set_vlsint32a(int index, ::int32_t value);
  void add_vlsint32a(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& vlsint32a() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_vlsint32a();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_vlsint32a() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_vlsint32a();

  public:
  // repeated sint64 VLSINT64A = 10;
  int vlsint64a_size() const;
  private:
  int _internal_vlsint64a_size() const;

  public:
  void clear_vlsint64a() ;
  ::int64_t vlsint64a(int index) const;
  void set_vlsint64a(int index, ::int64_t value);
  void add_vlsint64a(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& vlsint64a() const;
  ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL mutable_vlsint64a();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_vlsint64a() const;
  ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL _internal_mutable_vlsint64a();

  public:
  // repeated sfixed32 FLSINT32A = 11;
  int flsint32a_size() const;
  private:
  int _internal_flsint32a_size() const;

  public:
  void clear_flsint32a() ;
  ::int32_t flsint32a(int index) const;
  void set_flsint32a(int index, ::int32_t value);
  void add_flsint32a(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& flsint32a() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_flsint32a();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_flsint32a() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_flsint32a();

  public:
  // repeated sfixed64 FLSINT64A = 12;
  int flsint64a_size() const;
  private:
  int _internal_flsint64a_size() const;

  public:
  void clear_flsint64a() ;
  ::int64_t flsint64a(int index) const;
  void set_flsint64a(int index, ::int64_t value);
  void add_flsint64a(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& flsint64a() const;
  ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL mutable_flsint64a();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_flsint64a() const;
  ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL _internal_mutable_flsint64a();

  public:
  // repeated float FLOATA = 13;
  int floata_size() const;
  private:
  int _internal_floata_size() const;

  public:
  void clear_floata() ;
  float floata(int index) const;
  void set_floata(int index, float value);
  void add_floata(float value);
  const ::google::protobuf::RepeatedField<float>& floata() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_floata();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_floata() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_floata();

  public:
  // repeated double DOUBLEA = 14;
  int doublea_size() const;
  private:
  int _internal_doublea_size() const;

  public:
  void clear_doublea() ;
  double doublea(int index) const;
  void set_doublea(int index, double value);
  void add_doublea(double value);
  const ::google::protobuf::RepeatedField<double>& doublea() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_doublea();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_doublea() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_doublea();

  public:
  // repeated string STRINGA = 15;
  int stringa_size() const;
  private:
  int _internal_stringa_size() const;

  public:
  void clear_stringa() ;
  const ::std::string& stringa(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_stringa(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_stringa(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_stringa();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_stringa(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& stringa() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_stringa();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_stringa() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_stringa();

  public:
  // repeated bytes BYTESA = 16;
  int bytesa_size() const;
  private:
  int _internal_bytesa_size() const;

  public:
  void clear_bytesa() ;
  const ::std::string& bytesa(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_bytesa(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_bytesa(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_bytesa();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_bytesa(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& bytesa() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_bytesa();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_bytesa() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_bytesa();

  public:
  // optional string STRING = 7;
  bool has_string() const;
  void clear_string() ;
  const ::std::string& string() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_string(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_string();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_string();
  void set_allocated_string(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_string() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_string(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_string();

  public:
  // optional bytes BYTES = 8;
  bool has_bytes() const;
  void clear_bytes() ;
  const ::std::string& bytes() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_bytes(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_bytes();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_bytes();
  void set_allocated_bytes(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_bytes() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bytes(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_bytes();

  public:
  // optional sint64 VLSINT64 = 2;
  bool has_vlsint64() const;
  void clear_vlsint64() ;
  ::int64_t vlsint64() const;
  void set_vlsint64(::int64_t value);

  private:
  ::int64_t _internal_vlsint64() const;
  void _internal_set_vlsint64(::int64_t value);

  public:
  // optional sint32 VLSINT32 = 1;
  bool has_vlsint32() const;
  void clear_vlsint32() ;
  ::int32_t vlsint32() const;
  void set_vlsint32(::int32_t value);

  private:
  ::int32_t _internal_vlsint32() const;
  void _internal_set_vlsint32(::int32_t value);

  public:
  // optional sfixed32 FLSINT32 = 3;
  bool has_flsint32() const;
  void clear_flsint32() ;
  ::int32_t flsint32() const;
  void set_flsint32(::int32_t value);

  private:
  ::int32_t _internal_flsint32() const;
  void _internal_set_flsint32(::int32_t value);

  public:
  // optional sfixed64 FLSINT64 = 4;
  bool has_flsint64() const;
  void clear_flsint64() ;
  ::int64_t flsint64() const;
  void set_flsint64(::int64_t value);

  private:
  ::int64_t _internal_flsint64() const;
  void _internal_set_flsint64(::int64_t value);

  public:
  // optional double DOUBLE = 6;
  bool has_double_() const;
  void clear_double_() ;
  double double_() const;
  void set_double_(double value);

  private:
  double _internal_double_() const;
  void _internal_set_double_(double value);

  public:
  // optional float FLOAT = 5;
  bool has_float_() const;
  void clear_float_() ;
  float float_() const;
  void set_float_(float value);

  private:
  float _internal_float_() const;
  void _internal_set_float_(float value);

  public:
  // optional .xmsg.proto.Data.Type type = 17;
  bool has_type() const;
  void clear_type() ;
  ::xmsg::proto::Data_Type type() const;
  void set_type(::xmsg::proto::Data_Type value);

  private:
  ::xmsg::proto::Data_Type _internal_type() const;
  void _internal_set_type(::xmsg::proto::Data_Type value);

  public:
  // @@protoc_insertion_point(class_scope:xmsg.proto.Data)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 17,
                                   1, 53,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Data& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> vlsint32a_;
    ::google::protobuf::RepeatedField<::int64_t> vlsint64a_;
    ::google::protobuf::RepeatedField<::int32_t> flsint32a_;
    ::google::protobuf::RepeatedField<::int64_t> flsint64a_;
    ::google::protobuf::RepeatedField<float> floata_;
    ::google::protobuf::RepeatedField<double> doublea_;
    ::google::protobuf::RepeatedPtrField<::std::string> stringa_;
    ::google::protobuf::RepeatedPtrField<::std::string> bytesa_;
    ::google::protobuf::internal::ArenaStringPtr string_;
    ::google::protobuf::internal::ArenaStringPtr bytes_;
    ::int64_t vlsint64_;
    ::int32_t vlsint32_;
    ::int32_t flsint32_;
    ::int64_t flsint64_;
    double double__;
    float float__;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_data_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Data_class_data_;
// -------------------------------------------------------------------

class Payload_Item final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:xmsg.proto.Payload.Item) */ {
 public:
  inline Payload_Item() : Payload_Item(nullptr) {}
  ~Payload_Item() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Payload_Item* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Payload_Item));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Payload_Item(::google::protobuf::internal::ConstantInitialized);

  inline Payload_Item(const Payload_Item& from) : Payload_Item(nullptr, from) {}
  inline Payload_Item(Payload_Item&& from) noexcept
      : Payload_Item(nullptr, ::std::move(from)) {}
  inline Payload_Item& operator=(const Payload_Item& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload_Item& operator=(Payload_Item&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload_Item& default_instance() {
    return *reinterpret_cast<const Payload_Item*>(
        &_Payload_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Payload_Item& a, Payload_Item& b) { a.Swap(&b); }
  inline void Swap(Payload_Item* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload_Item* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload_Item* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Payload_Item>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Payload_Item& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Payload_Item& from) { Payload_Item::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Payload_Item* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "xmsg.proto.Payload.Item"; }

 protected:
  explicit Payload_Item(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Payload_Item(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Payload_Item& from);
  Payload_Item(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Payload_Item&& from) noexcept
      : Payload_Item(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kDataFieldNumber = 2,
  };
  // required string name = 1;
  bool has_name() const;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // required .xmsg.proto.Data data = 2;
  bool has_data() const;
  void clear_data() ;
  const ::xmsg::proto::Data& data() const;
  [[nodiscard]] ::xmsg::proto::Data* PROTOBUF_NULLABLE release_data();
  ::xmsg::proto::Data* PROTOBUF_NONNULL mutable_data();
  void set_allocated_data(::xmsg::proto::Data* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_data(::xmsg::proto::Data* PROTOBUF_NULLABLE value);
  ::xmsg::proto::Data* PROTOBUF_NULLABLE unsafe_arena_release_data();

  private:
  const ::xmsg::proto::Data& _internal_data() const;
  ::xmsg::proto::Data* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:xmsg.proto.Payload.Item)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Payload_Item& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::xmsg::proto::Data* PROTOBUF_NULLABLE data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_data_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Payload_Item_class_data_;
// -------------------------------------------------------------------

class Payload final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:xmsg.proto.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Payload* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Payload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Payload(::google::protobuf::internal::ConstantInitialized);

  inline Payload(const Payload& from) : Payload(nullptr, from) {}
  inline Payload(Payload&& from) noexcept
      : Payload(nullptr, ::std::move(from)) {}
  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload& default_instance() {
    return *reinterpret_cast<const Payload*>(
        &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Payload& a, Payload& b) { a.Swap(&b); }
  inline void Swap(Payload* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Payload>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Payload& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Payload& from) { Payload::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Payload* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "xmsg.proto.Payload"; }

 protected:
  explicit Payload(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Payload(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Payload& from);
  Payload(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Payload&& from) noexcept
      : Payload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Item = Payload_Item;

  // accessors -------------------------------------------------------
  enum : int {
    kItemFieldNumber = 1,
  };
  // repeated .xmsg.proto.Payload.Item item = 1;
  int item_size() const;
  private:
  int _internal_item_size() const;

  public:
  void clear_item() ;
  ::xmsg::proto::Payload_Item* PROTOBUF_NONNULL mutable_item(int index);
  ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>* PROTOBUF_NONNULL mutable_item();

  private:
  const ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>& _internal_item() const;
  ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>* PROTOBUF_NONNULL _internal_mutable_item();
  public:
  const ::xmsg::proto::Payload_Item& item(int index) const;
  ::xmsg::proto::Payload_Item* PROTOBUF_NONNULL add_item();
  const ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>& item() const;
  // @@protoc_insertion_point(class_scope:xmsg.proto.Payload)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Payload& from_msg);
    ::google::protobuf::RepeatedPtrField< ::xmsg::proto::Payload_Item > item_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_data_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Payload_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Data

// optional sint32 VLSINT32 = 1;
inline bool Data::has_vlsint32() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Data::clear_vlsint32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vlsint32_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t Data::vlsint32() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.VLSINT32)
  return _internal_vlsint32();
}
inline void Data::set_vlsint32(::int32_t value) {
  _internal_set_vlsint32(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.VLSINT32)
}
inline ::int32_t Data::_internal_vlsint32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vlsint32_;
}
inline void Data::_internal_set_vlsint32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vlsint32_ = value;
}

// optional sint64 VLSINT64 = 2;
inline bool Data::has_vlsint64() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Data::clear_vlsint64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vlsint64_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t Data::vlsint64() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.VLSINT64)
  return _internal_vlsint64();
}
inline void Data::set_vlsint64(::int64_t value) {
  _internal_set_vlsint64(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.VLSINT64)
}
inline ::int64_t Data::_internal_vlsint64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vlsint64_;
}
inline void Data::_internal_set_vlsint64(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vlsint64_ = value;
}

// optional sfixed32 FLSINT32 = 3;
inline bool Data::has_flsint32() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Data::clear_flsint32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flsint32_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t Data::flsint32() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.FLSINT32)
  return _internal_flsint32();
}
inline void Data::set_flsint32(::int32_t value) {
  _internal_set_flsint32(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.FLSINT32)
}
inline ::int32_t Data::_internal_flsint32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flsint32_;
}
inline void Data::_internal_set_flsint32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flsint32_ = value;
}

// optional sfixed64 FLSINT64 = 4;
inline bool Data::has_flsint64() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Data::clear_flsint64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flsint64_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int64_t Data::flsint64() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.FLSINT64)
  return _internal_flsint64();
}
inline void Data::set_flsint64(::int64_t value) {
  _internal_set_flsint64(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.FLSINT64)
}
inline ::int64_t Data::_internal_flsint64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flsint64_;
}
inline void Data::_internal_set_flsint64(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flsint64_ = value;
}

// optional float FLOAT = 5;
inline bool Data::has_float_() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void Data::clear_float_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.float__ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline float Data::float_() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.FLOAT)
  return _internal_float_();
}
inline void Data::set_float_(float value) {
  _internal_set_float_(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.FLOAT)
}
inline float Data::_internal_float_() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.float__;
}
inline void Data::_internal_set_float_(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.float__ = value;
}

// optional double DOUBLE = 6;
inline bool Data::has_double_() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void Data::clear_double_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.double__ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline double Data::double_() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.DOUBLE)
  return _internal_double_();
}
inline void Data::set_double_(double value) {
  _internal_set_double_(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.DOUBLE)
}
inline double Data::_internal_double_() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.double__;
}
inline void Data::_internal_set_double_(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.double__ = value;
}

// optional string STRING = 7;
inline bool Data::has_string() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Data::clear_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Data::string() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.STRING)
  return _internal_string();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Data::set_string(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.string_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.STRING)
}
inline ::std::string* PROTOBUF_NONNULL Data::mutable_string()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_string();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Data.STRING)
  return _s;
}
inline const ::std::string& Data::_internal_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.string_.Get();
}
inline void Data::_internal_set_string(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.string_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Data::_internal_mutable_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.string_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Data::release_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Data.STRING)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.string_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.string_.Set("", GetArena());
  }
  return released;
}
inline void Data::set_allocated_string(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.string_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.string_.IsDefault()) {
    _impl_.string_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Data.STRING)
}

// optional bytes BYTES = 8;
inline bool Data::has_bytes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Data::clear_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bytes_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& Data::bytes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.BYTES)
  return _internal_bytes();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Data::set_bytes(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.bytes_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.BYTES)
}
inline ::std::string* PROTOBUF_NONNULL Data::mutable_bytes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_bytes();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Data.BYTES)
  return _s;
}
inline const ::std::string& Data::_internal_bytes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bytes_.Get();
}
inline void Data::_internal_set_bytes(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.bytes_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Data::_internal_mutable_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.bytes_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Data::release_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Data.BYTES)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.bytes_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bytes_.Set("", GetArena());
  }
  return released;
}
inline void Data::set_allocated_bytes(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.bytes_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bytes_.IsDefault()) {
    _impl_.bytes_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Data.BYTES)
}

// repeated sint32 VLSINT32A = 9;
inline int Data::_internal_vlsint32a_size() const {
  return _internal_vlsint32a().size();
}
inline int Data::vlsint32a_size() const {
  return _internal_vlsint32a_size();
}
inline void Data::clear_vlsint32a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vlsint32a_.Clear();
}
inline ::int32_t Data::vlsint32a(int index) const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.VLSINT32A)
  return _internal_vlsint32a().Get(index);
}
inline void Data::set_vlsint32a(int index, ::int32_t value) {
  _internal_mutable_vlsint32a()->Set(index, value);
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.VLSINT32A)
}
inline void Data::add_vlsint32a(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_vlsint32a()->Add(value);
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.VLSINT32A)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& Data::vlsint32a() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.VLSINT32A)
  return _internal_vlsint32a();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL Data::mutable_vlsint32a()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.VLSINT32A)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vlsint32a();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
Data::_internal_vlsint32a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vlsint32a_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
Data::_internal_mutable_vlsint32a() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vlsint32a_;
}

// repeated sint64 VLSINT64A = 10;
inline int Data::_internal_vlsint64a_size() const {
  return _internal_vlsint64a().size();
}
inline int Data::vlsint64a_size() const {
  return _internal_vlsint64a_size();
}
inline void Data::clear_vlsint64a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vlsint64a_.Clear();
}
inline ::int64_t Data::vlsint64a(int index) const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.VLSINT64A)
  return _internal_vlsint64a().Get(index);
}
inline void Data::set_vlsint64a(int index, ::int64_t value) {
  _internal_mutable_vlsint64a()->Set(index, value);
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.VLSINT64A)
}
inline void Data::add_vlsint64a(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_vlsint64a()->Add(value);
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.VLSINT64A)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& Data::vlsint64a() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.VLSINT64A)
  return _internal_vlsint64a();
}
inline ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL Data::mutable_vlsint64a()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.VLSINT64A)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vlsint64a();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
Data::_internal_vlsint64a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vlsint64a_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL
Data::_internal_mutable_vlsint64a() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vlsint64a_;
}

// repeated sfixed32 FLSINT32A = 11;
inline int Data::_internal_flsint32a_size() const {
  return _internal_flsint32a().size();
}
inline int Data::flsint32a_size() const {
  return _internal_flsint32a_size();
}
inline void Data::clear_flsint32a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flsint32a_.Clear();
}
inline ::int32_t Data::flsint32a(int index) const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.FLSINT32A)
  return _internal_flsint32a().Get(index);
}
inline void Data::set_flsint32a(int index, ::int32_t value) {
  _internal_mutable_flsint32a()->Set(index, value);
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.FLSINT32A)
}
inline void Data::add_flsint32a(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_flsint32a()->Add(value);
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.FLSINT32A)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& Data::flsint32a() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.FLSINT32A)
  return _internal_flsint32a();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL Data::mutable_flsint32a()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.FLSINT32A)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_flsint32a();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
Data::_internal_flsint32a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flsint32a_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
Data::_internal_mutable_flsint32a() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.flsint32a_;
}

// repeated sfixed64 FLSINT64A = 12;
inline int Data::_internal_flsint64a_size() const {
  return _internal_flsint64a().size();
}
inline int Data::flsint64a_size() const {
  return _internal_flsint64a_size();
}
inline void Data::clear_flsint64a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flsint64a_.Clear();
}
inline ::int64_t Data::flsint64a(int index) const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.FLSINT64A)
  return _internal_flsint64a().Get(index);
}
inline void Data::set_flsint64a(int index, ::int64_t value) {
  _internal_mutable_flsint64a()->Set(index, value);
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.FLSINT64A)
}
inline void Data::add_flsint64a(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_flsint64a()->Add(value);
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.FLSINT64A)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& Data::flsint64a() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.FLSINT64A)
  return _internal_flsint64a();
}
inline ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL Data::mutable_flsint64a()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.FLSINT64A)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_flsint64a();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
Data::_internal_flsint64a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flsint64a_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* PROTOBUF_NONNULL
Data::_internal_mutable_flsint64a() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.flsint64a_;
}

// repeated float FLOATA = 13;
inline int Data::_internal_floata_size() const {
  return _internal_floata().size();
}
inline int Data::floata_size() const {
  return _internal_floata_size();
}
inline void Data::clear_floata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.floata_.Clear();
}
inline float Data::floata(int index) const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.FLOATA)
  return _internal_floata().Get(index);
}
inline void Data::set_floata(int index, float value) {
  _internal_mutable_floata()->Set(index, value);
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.FLOATA)
}
inline void Data::add_floata(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_floata()->Add(value);
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.FLOATA)
}
inline const ::google::protobuf::RepeatedField<float>& Data::floata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.FLOATA)
  return _internal_floata();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL Data::mutable_floata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.FLOATA)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_floata();
}
inline const ::google::protobuf::RepeatedField<float>&
Data::_internal_floata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.floata_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
Data::_internal_mutable_floata() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.floata_;
}

// repeated double DOUBLEA = 14;
inline int Data::_internal_doublea_size() const {
  return _internal_doublea().size();
}
inline int Data::doublea_size() const {
  return _internal_doublea_size();
}
inline void Data::clear_doublea() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.doublea_.Clear();
}
inline double Data::doublea(int index) const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.DOUBLEA)
  return _internal_doublea().Get(index);
}
inline void Data::set_doublea(int index, double value) {
  _internal_mutable_doublea()->Set(index, value);
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.DOUBLEA)
}
inline void Data::add_doublea(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_doublea()->Add(value);
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.DOUBLEA)
}
inline const ::google::protobuf::RepeatedField<double>& Data::doublea() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.DOUBLEA)
  return _internal_doublea();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL Data::mutable_doublea()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.DOUBLEA)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_doublea();
}
inline const ::google::protobuf::RepeatedField<double>&
Data::_internal_doublea() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.doublea_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
Data::_internal_mutable_doublea() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.doublea_;
}

// repeated string STRINGA = 15;
inline int Data::_internal_stringa_size() const {
  return _internal_stringa().size();
}
inline int Data::stringa_size() const {
  return _internal_stringa_size();
}
inline void Data::clear_stringa() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stringa_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL Data::add_stringa()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_stringa()->Add();
  // @@protoc_insertion_point(field_add_mutable:xmsg.proto.Data.STRINGA)
  return _s;
}
inline const ::std::string& Data::stringa(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.STRINGA)
  return _internal_stringa().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Data::mutable_stringa(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Data.STRINGA)
  return _internal_mutable_stringa()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Data::set_stringa(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_stringa()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.STRINGA)
}
template <typename Arg_, typename... Args_>
inline void Data::add_stringa(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_stringa(),
                               ::std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.STRINGA)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Data::stringa()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.STRINGA)
  return _internal_stringa();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Data::mutable_stringa() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.STRINGA)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_stringa();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Data::_internal_stringa() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stringa_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Data::_internal_mutable_stringa() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.stringa_;
}

// repeated bytes BYTESA = 16;
inline int Data::_internal_bytesa_size() const {
  return _internal_bytesa().size();
}
inline int Data::bytesa_size() const {
  return _internal_bytesa_size();
}
inline void Data::clear_bytesa() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bytesa_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL Data::add_bytesa()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_bytesa()->Add();
  // @@protoc_insertion_point(field_add_mutable:xmsg.proto.Data.BYTESA)
  return _s;
}
inline const ::std::string& Data::bytesa(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.BYTESA)
  return _internal_bytesa().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Data::mutable_bytesa(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Data.BYTESA)
  return _internal_mutable_bytesa()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Data::set_bytesa(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_bytesa()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.BYTESA)
}
template <typename Arg_, typename... Args_>
inline void Data::add_bytesa(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_bytesa(),
                               ::std::forward<Arg_>(value),
                               args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_add:xmsg.proto.Data.BYTESA)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Data::bytesa()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Data.BYTESA)
  return _internal_bytesa();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Data::mutable_bytesa() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Data.BYTESA)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_bytesa();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Data::_internal_bytesa() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bytesa_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Data::_internal_mutable_bytesa() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.bytesa_;
}

// optional .xmsg.proto.Data.Type type = 17;
inline bool Data::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void Data::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 1;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::xmsg::proto::Data_Type Data::type() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Data.type)
  return _internal_type();
}
inline void Data::set_type(::xmsg::proto::Data_Type value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Data.type)
}
inline ::xmsg::proto::Data_Type Data::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::xmsg::proto::Data_Type>(_impl_.type_);
}
inline void Data::_internal_set_type(::xmsg::proto::Data_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::xmsg::proto::Data_Type_internal_data_));
                                          _impl_.type_ = value;
}

// -------------------------------------------------------------------

// Payload_Item

// required string name = 1;
inline bool Payload_Item::has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Payload_Item::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Payload_Item::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Payload.Item.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Payload_Item::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Payload.Item.name)
}
inline ::std::string* PROTOBUF_NONNULL Payload_Item::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Payload.Item.name)
  return _s;
}
inline const ::std::string& Payload_Item::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Payload_Item::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Payload_Item::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Payload_Item::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Payload.Item.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void Payload_Item::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Payload.Item.name)
}

// required .xmsg.proto.Data data = 2;
inline bool Payload_Item::has_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.data_ != nullptr);
  return value;
}
inline void Payload_Item::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::xmsg::proto::Data& Payload_Item::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::xmsg::proto::Data* p = _impl_.data_;
  return p != nullptr ? *p : reinterpret_cast<const ::xmsg::proto::Data&>(::xmsg::proto::_Data_default_instance_);
}
inline const ::xmsg::proto::Data& Payload_Item::data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Payload.Item.data)
  return _internal_data();
}
inline void Payload_Item::unsafe_arena_set_allocated_data(
    ::xmsg::proto::Data* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.data_);
  }
  _impl_.data_ = reinterpret_cast<::xmsg::proto::Data*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xmsg.proto.Payload.Item.data)
}
inline ::xmsg::proto::Data* PROTOBUF_NULLABLE Payload_Item::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::xmsg::proto::Data* released = _impl_.data_;
  _impl_.data_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::xmsg::proto::Data* PROTOBUF_NULLABLE Payload_Item::unsafe_arena_release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Payload.Item.data)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::xmsg::proto::Data* temp = _impl_.data_;
  _impl_.data_ = nullptr;
  return temp;
}
inline ::xmsg::proto::Data* PROTOBUF_NONNULL Payload_Item::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.data_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::xmsg::proto::Data>(GetArena());
    _impl_.data_ = reinterpret_cast<::xmsg::proto::Data*>(p);
  }
  return _impl_.data_;
}
inline ::xmsg::proto::Data* PROTOBUF_NONNULL Payload_Item::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::xmsg::proto::Data* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Payload.Item.data)
  return _msg;
}
inline void Payload_Item::set_allocated_data(::xmsg::proto::Data* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.data_ = reinterpret_cast<::xmsg::proto::Data*>(value);
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Payload.Item.data)
}

// -------------------------------------------------------------------

// Payload

// repeated .xmsg.proto.Payload.Item item = 1;
inline int Payload::_internal_item_size() const {
  return _internal_item().size();
}
inline int Payload::item_size() const {
  return _internal_item_size();
}
inline void Payload::clear_item() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_.Clear();
}
inline ::xmsg::proto::Payload_Item* PROTOBUF_NONNULL Payload::mutable_item(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Payload.item)
  return _internal_mutable_item()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>* PROTOBUF_NONNULL Payload::mutable_item()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:xmsg.proto.Payload.item)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_item();
}
inline const ::xmsg::proto::Payload_Item& Payload::item(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Payload.item)
  return _internal_item().Get(index);
}
inline ::xmsg::proto::Payload_Item* PROTOBUF_NONNULL Payload::add_item()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::xmsg::proto::Payload_Item* _add = _internal_mutable_item()->Add();
  // @@protoc_insertion_point(field_add:xmsg.proto.Payload.item)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>& Payload::item() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:xmsg.proto.Payload.item)
  return _internal_item();
}
inline const ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>&
Payload::_internal_item() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_;
}
inline ::google::protobuf::RepeatedPtrField<::xmsg::proto::Payload_Item>* PROTOBUF_NONNULL
Payload::_internal_mutable_item() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.item_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace xmsg


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::xmsg::proto::Data_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::xmsg::proto::Data_Type>() {
  return ::xmsg::proto::Data_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // data_2eproto_2epb_2eh
