// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf C++ Version: 6.31.1

#ifndef meta_2eproto_2epb_2eh
#define meta_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_meta_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_meta_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_meta_2eproto;
}  // extern "C"
namespace xmsg {
namespace proto {
enum Meta_ControlAction : int;
extern const uint32_t Meta_ControlAction_internal_data_[];
enum Meta_Endian : int;
extern const uint32_t Meta_Endian_internal_data_[];
enum Meta_Status : int;
extern const uint32_t Meta_Status_internal_data_[];
enum Meta_SubControlAction : int;
extern const uint32_t Meta_SubControlAction_internal_data_[];
class Meta;
struct MetaDefaultTypeInternal;
extern MetaDefaultTypeInternal _Meta_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Meta_class_data_;
}  // namespace proto
}  // namespace xmsg
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::xmsg::proto::Meta_ControlAction_internal_data_>
    internal::EnumTraitsImpl::value<::xmsg::proto::Meta_ControlAction>;
template <>
internal::EnumTraitsT<::xmsg::proto::Meta_Endian_internal_data_>
    internal::EnumTraitsImpl::value<::xmsg::proto::Meta_Endian>;
template <>
internal::EnumTraitsT<::xmsg::proto::Meta_Status_internal_data_>
    internal::EnumTraitsImpl::value<::xmsg::proto::Meta_Status>;
template <>
internal::EnumTraitsT<::xmsg::proto::Meta_SubControlAction_internal_data_>
    internal::EnumTraitsImpl::value<::xmsg::proto::Meta_SubControlAction>;
}  // namespace protobuf
}  // namespace google

namespace xmsg {
namespace proto {
enum Meta_Status : int {
  Meta_Status_INFO = 1,
  Meta_Status_WARNING = 2,
  Meta_Status_ERROR = 3,
};

extern const uint32_t Meta_Status_internal_data_[];
inline constexpr Meta_Status Meta_Status_Status_MIN =
    static_cast<Meta_Status>(1);
inline constexpr Meta_Status Meta_Status_Status_MAX =
    static_cast<Meta_Status>(3);
inline bool Meta_Status_IsValid(int value) {
  return 1 <= value && value <= 3;
}
inline constexpr int Meta_Status_Status_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Meta_Status_descriptor();
template <typename T>
const ::std::string& Meta_Status_Name(T value) {
  static_assert(::std::is_same<T, Meta_Status>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return Meta_Status_Name(static_cast<Meta_Status>(value));
}
template <>
inline const ::std::string& Meta_Status_Name(Meta_Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Meta_Status_descriptor, 1, 3>(
      static_cast<int>(value));
}
inline bool Meta_Status_Parse(
    ::absl::string_view name, Meta_Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Meta_Status>(Meta_Status_descriptor(), name,
                                           value);
}
enum Meta_Endian : int {
  Meta_Endian_Little = 1,
  Meta_Endian_Big = 2,
};

extern const uint32_t Meta_Endian_internal_data_[];
inline constexpr Meta_Endian Meta_Endian_Endian_MIN =
    static_cast<Meta_Endian>(1);
inline constexpr Meta_Endian Meta_Endian_Endian_MAX =
    static_cast<Meta_Endian>(2);
inline bool Meta_Endian_IsValid(int value) {
  return 1 <= value && value <= 2;
}
inline constexpr int Meta_Endian_Endian_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Meta_Endian_descriptor();
template <typename T>
const ::std::string& Meta_Endian_Name(T value) {
  static_assert(::std::is_same<T, Meta_Endian>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Endian_Name().");
  return Meta_Endian_Name(static_cast<Meta_Endian>(value));
}
template <>
inline const ::std::string& Meta_Endian_Name(Meta_Endian value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Meta_Endian_descriptor, 1, 2>(
      static_cast<int>(value));
}
inline bool Meta_Endian_Parse(
    ::absl::string_view name, Meta_Endian* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Meta_Endian>(Meta_Endian_descriptor(), name,
                                           value);
}
enum Meta_ControlAction : int {
  Meta_ControlAction_EXECUTE = 0,
  Meta_ControlAction_CONFIGURE = 1,
};

extern const uint32_t Meta_ControlAction_internal_data_[];
inline constexpr Meta_ControlAction Meta_ControlAction_ControlAction_MIN =
    static_cast<Meta_ControlAction>(0);
inline constexpr Meta_ControlAction Meta_ControlAction_ControlAction_MAX =
    static_cast<Meta_ControlAction>(1);
inline bool Meta_ControlAction_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int Meta_ControlAction_ControlAction_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Meta_ControlAction_descriptor();
template <typename T>
const ::std::string& Meta_ControlAction_Name(T value) {
  static_assert(::std::is_same<T, Meta_ControlAction>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ControlAction_Name().");
  return Meta_ControlAction_Name(static_cast<Meta_ControlAction>(value));
}
template <>
inline const ::std::string& Meta_ControlAction_Name(Meta_ControlAction value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Meta_ControlAction_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool Meta_ControlAction_Parse(
    ::absl::string_view name, Meta_ControlAction* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Meta_ControlAction>(Meta_ControlAction_descriptor(), name,
                                           value);
}
enum Meta_SubControlAction : int {
  Meta_SubControlAction_SKIP = 0,
};

extern const uint32_t Meta_SubControlAction_internal_data_[];
inline constexpr Meta_SubControlAction Meta_SubControlAction_SubControlAction_MIN =
    static_cast<Meta_SubControlAction>(0);
inline constexpr Meta_SubControlAction Meta_SubControlAction_SubControlAction_MAX =
    static_cast<Meta_SubControlAction>(0);
inline bool Meta_SubControlAction_IsValid(int value) {
  return 0 <= value && value <= 0;
}
inline constexpr int Meta_SubControlAction_SubControlAction_ARRAYSIZE = 0 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Meta_SubControlAction_descriptor();
template <typename T>
const ::std::string& Meta_SubControlAction_Name(T value) {
  static_assert(::std::is_same<T, Meta_SubControlAction>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to SubControlAction_Name().");
  return Meta_SubControlAction_Name(static_cast<Meta_SubControlAction>(value));
}
template <>
inline const ::std::string& Meta_SubControlAction_Name(Meta_SubControlAction value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Meta_SubControlAction_descriptor, 0, 0>(
      static_cast<int>(value));
}
inline bool Meta_SubControlAction_Parse(
    ::absl::string_view name, Meta_SubControlAction* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Meta_SubControlAction>(Meta_SubControlAction_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Meta final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:xmsg.proto.Meta) */ {
 public:
  inline Meta() : Meta(nullptr) {}
  ~Meta() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Meta* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Meta));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Meta(::google::protobuf::internal::ConstantInitialized);

  inline Meta(const Meta& from) : Meta(nullptr, from) {}
  inline Meta(Meta&& from) noexcept
      : Meta(nullptr, ::std::move(from)) {}
  inline Meta& operator=(const Meta& from) {
    CopyFrom(from);
    return *this;
  }
  inline Meta& operator=(Meta&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Meta& default_instance() {
    return *reinterpret_cast<const Meta*>(
        &_Meta_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Meta& a, Meta& b) { a.Swap(&b); }
  inline void Swap(Meta* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Meta* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Meta* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Meta>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Meta& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Meta& from) { Meta::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Meta* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "xmsg.proto.Meta"; }

 protected:
  explicit Meta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Meta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Meta& from);
  Meta(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Meta&& from) noexcept
      : Meta(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Status = Meta_Status;
  static constexpr Status INFO = Meta_Status_INFO;
  static constexpr Status WARNING = Meta_Status_WARNING;
  static constexpr Status ERROR = Meta_Status_ERROR;
  static inline bool Status_IsValid(int value) {
    return Meta_Status_IsValid(value);
  }
  static constexpr Status Status_MIN = Meta_Status_Status_MIN;
  static constexpr Status Status_MAX = Meta_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE = Meta_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
    return Meta_Status_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Status_Name(T value) {
    return Meta_Status_Name(value);
  }
  static inline bool Status_Parse(
      ::absl::string_view name, Status* PROTOBUF_NONNULL value) {
    return Meta_Status_Parse(name, value);
  }
  using Endian = Meta_Endian;
  static constexpr Endian Little = Meta_Endian_Little;
  static constexpr Endian Big = Meta_Endian_Big;
  static inline bool Endian_IsValid(int value) {
    return Meta_Endian_IsValid(value);
  }
  static constexpr Endian Endian_MIN = Meta_Endian_Endian_MIN;
  static constexpr Endian Endian_MAX = Meta_Endian_Endian_MAX;
  static constexpr int Endian_ARRAYSIZE = Meta_Endian_Endian_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Endian_descriptor() {
    return Meta_Endian_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Endian_Name(T value) {
    return Meta_Endian_Name(value);
  }
  static inline bool Endian_Parse(
      ::absl::string_view name, Endian* PROTOBUF_NONNULL value) {
    return Meta_Endian_Parse(name, value);
  }
  using ControlAction = Meta_ControlAction;
  static constexpr ControlAction EXECUTE = Meta_ControlAction_EXECUTE;
  static constexpr ControlAction CONFIGURE = Meta_ControlAction_CONFIGURE;
  static inline bool ControlAction_IsValid(int value) {
    return Meta_ControlAction_IsValid(value);
  }
  static constexpr ControlAction ControlAction_MIN = Meta_ControlAction_ControlAction_MIN;
  static constexpr ControlAction ControlAction_MAX = Meta_ControlAction_ControlAction_MAX;
  static constexpr int ControlAction_ARRAYSIZE = Meta_ControlAction_ControlAction_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ControlAction_descriptor() {
    return Meta_ControlAction_descriptor();
  }
  template <typename T>
  static inline const ::std::string& ControlAction_Name(T value) {
    return Meta_ControlAction_Name(value);
  }
  static inline bool ControlAction_Parse(
      ::absl::string_view name, ControlAction* PROTOBUF_NONNULL value) {
    return Meta_ControlAction_Parse(name, value);
  }
  using SubControlAction = Meta_SubControlAction;
  static constexpr SubControlAction SKIP = Meta_SubControlAction_SKIP;
  static inline bool SubControlAction_IsValid(int value) {
    return Meta_SubControlAction_IsValid(value);
  }
  static constexpr SubControlAction SubControlAction_MIN = Meta_SubControlAction_SubControlAction_MIN;
  static constexpr SubControlAction SubControlAction_MAX = Meta_SubControlAction_SubControlAction_MAX;
  static constexpr int SubControlAction_ARRAYSIZE = Meta_SubControlAction_SubControlAction_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SubControlAction_descriptor() {
    return Meta_SubControlAction_descriptor();
  }
  template <typename T>
  static inline const ::std::string& SubControlAction_Name(T value) {
    return Meta_SubControlAction_Name(value);
  }
  static inline bool SubControlAction_Parse(
      ::absl::string_view name, SubControlAction* PROTOBUF_NONNULL value) {
    return Meta_SubControlAction_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kVersionFieldNumber = 1,
    kDescriptionFieldNumber = 2,
    kAuthorFieldNumber = 3,
    kSenderFieldNumber = 6,
    kSenderStateFieldNumber = 7,
    kCompositionFieldNumber = 10,
    kDataTypeFieldNumber = 14,
    kDatTypeDescriptionFieldNumber = 15,
    kReplyToFieldNumber = 16,
    kSeverityIdFieldNumber = 5,
    kCommunicationIdFieldNumber = 8,
    kExecutionTimeFieldNumber = 11,
    kActionFieldNumber = 12,
    kControlFieldNumber = 13,
    kStatusFieldNumber = 4,
    kByteOrderFieldNumber = 17,
  };
  // optional string version = 1;
  bool has_version() const;
  void clear_version() ;
  const ::std::string& version() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_version(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_version();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_version();
  void set_allocated_version(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_version() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_version(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_version();

  public:
  // optional string description = 2;
  bool has_description() const;
  void clear_description() ;
  const ::std::string& description() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_description(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_description();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_description();
  void set_allocated_description(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_description() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_description(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_description();

  public:
  // optional string author = 3;
  bool has_author() const;
  void clear_author() ;
  const ::std::string& author() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_author(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_author();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_author();
  void set_allocated_author(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_author() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_author(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_author();

  public:
  // optional string sender = 6;
  bool has_sender() const;
  void clear_sender() ;
  const ::std::string& sender() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sender(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sender();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sender();
  void set_allocated_sender(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sender() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sender(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sender();

  public:
  // optional string senderState = 7;
  bool has_senderstate() const;
  void clear_senderstate() ;
  const ::std::string& senderstate() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_senderstate(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_senderstate();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_senderstate();
  void set_allocated_senderstate(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_senderstate() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_senderstate(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_senderstate();

  public:
  // optional string composition = 10;
  bool has_composition() const;
  void clear_composition() ;
  const ::std::string& composition() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_composition(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_composition();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_composition();
  void set_allocated_composition(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_composition() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_composition(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_composition();

  public:
  // required string dataType = 14;
  bool has_datatype() const;
  void clear_datatype() ;
  const ::std::string& datatype() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_datatype(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_datatype();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_datatype();
  void set_allocated_datatype(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_datatype() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_datatype(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_datatype();

  public:
  // optional string datTypeDescription = 15;
  bool has_dattypedescription() const;
  void clear_dattypedescription() ;
  const ::std::string& dattypedescription() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dattypedescription(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dattypedescription();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dattypedescription();
  void set_allocated_dattypedescription(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dattypedescription() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dattypedescription(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dattypedescription();

  public:
  // optional string replyTo = 16;
  bool has_replyto() const;
  void clear_replyto() ;
  const ::std::string& replyto() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_replyto(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_replyto();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_replyto();
  void set_allocated_replyto(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_replyto() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_replyto(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_replyto();

  public:
  // optional sfixed32 severityId = 5;
  bool has_severityid() const;
  void clear_severityid() ;
  ::int32_t severityid() const;
  void set_severityid(::int32_t value);

  private:
  ::int32_t _internal_severityid() const;
  void _internal_set_severityid(::int32_t value);

  public:
  // optional fixed32 communicationId = 8;
  bool has_communicationid() const;
  void clear_communicationid() ;
  ::uint32_t communicationid() const;
  void set_communicationid(::uint32_t value);

  private:
  ::uint32_t _internal_communicationid() const;
  void _internal_set_communicationid(::uint32_t value);

  public:
  // optional sfixed64 executionTime = 11;
  bool has_executiontime() const;
  void clear_executiontime() ;
  ::int64_t executiontime() const;
  void set_executiontime(::int64_t value);

  private:
  ::int64_t _internal_executiontime() const;
  void _internal_set_executiontime(::int64_t value);

  public:
  // optional .xmsg.proto.Meta.ControlAction action = 12;
  bool has_action() const;
  void clear_action() ;
  ::xmsg::proto::Meta_ControlAction action() const;
  void set_action(::xmsg::proto::Meta_ControlAction value);

  private:
  ::xmsg::proto::Meta_ControlAction _internal_action() const;
  void _internal_set_action(::xmsg::proto::Meta_ControlAction value);

  public:
  // optional .xmsg.proto.Meta.SubControlAction control = 13;
  bool has_control() const;
  void clear_control() ;
  ::xmsg::proto::Meta_SubControlAction control() const;
  void set_control(::xmsg::proto::Meta_SubControlAction value);

  private:
  ::xmsg::proto::Meta_SubControlAction _internal_control() const;
  void _internal_set_control(::xmsg::proto::Meta_SubControlAction value);

  public:
  // optional .xmsg.proto.Meta.Status status = 4;
  bool has_status() const;
  void clear_status() ;
  ::xmsg::proto::Meta_Status status() const;
  void set_status(::xmsg::proto::Meta_Status value);

  private:
  ::xmsg::proto::Meta_Status _internal_status() const;
  void _internal_set_status(::xmsg::proto::Meta_Status value);

  public:
  // optional .xmsg.proto.Meta.Endian byteOrder = 17;
  bool has_byteorder() const;
  void clear_byteorder() ;
  ::xmsg::proto::Meta_Endian byteorder() const;
  void set_byteorder(::xmsg::proto::Meta_Endian value);

  private:
  ::xmsg::proto::Meta_Endian _internal_byteorder() const;
  void _internal_set_byteorder(::xmsg::proto::Meta_Endian value);

  public:
  // @@protoc_insertion_point(class_scope:xmsg.proto.Meta)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 16,
                                   4, 125,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Meta& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr version_;
    ::google::protobuf::internal::ArenaStringPtr description_;
    ::google::protobuf::internal::ArenaStringPtr author_;
    ::google::protobuf::internal::ArenaStringPtr sender_;
    ::google::protobuf::internal::ArenaStringPtr senderstate_;
    ::google::protobuf::internal::ArenaStringPtr composition_;
    ::google::protobuf::internal::ArenaStringPtr datatype_;
    ::google::protobuf::internal::ArenaStringPtr dattypedescription_;
    ::google::protobuf::internal::ArenaStringPtr replyto_;
    ::int32_t severityid_;
    ::uint32_t communicationid_;
    ::int64_t executiontime_;
    int action_;
    int control_;
    int status_;
    int byteorder_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meta_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Meta_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Meta

// optional string version = 1;
inline bool Meta::has_version() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Meta::clear_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Meta::version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.version)
  return _internal_version();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_version(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.version)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.version)
  return _s;
}
inline const ::std::string& Meta::_internal_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.version_.Get();
}
inline void Meta::_internal_set_version(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.version_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.version_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.version)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.version_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.version_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_version(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.version_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.version_.IsDefault()) {
    _impl_.version_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.version)
}

// optional string description = 2;
inline bool Meta::has_description() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Meta::clear_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& Meta::description() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.description)
  return _internal_description();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_description(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.description_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.description)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_description()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.description)
  return _s;
}
inline const ::std::string& Meta::_internal_description() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.description_.Get();
}
inline void Meta::_internal_set_description(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.description_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.description_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.description)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.description_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.description_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_description(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.description_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.description)
}

// optional string author = 3;
inline bool Meta::has_author() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Meta::clear_author() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.author_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& Meta::author() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.author)
  return _internal_author();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_author(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.author_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.author)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_author()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_author();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.author)
  return _s;
}
inline const ::std::string& Meta::_internal_author() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.author_.Get();
}
inline void Meta::_internal_set_author(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.author_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_author() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.author_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_author() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.author)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.author_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.author_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_author(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.author_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.author_.IsDefault()) {
    _impl_.author_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.author)
}

// optional .xmsg.proto.Meta.Status status = 4;
inline bool Meta::has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline void Meta::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 1;
  _impl_._has_bits_[0] &= ~0x00004000u;
}
inline ::xmsg::proto::Meta_Status Meta::status() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.status)
  return _internal_status();
}
inline void Meta::set_status(::xmsg::proto::Meta_Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00004000u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.status)
}
inline ::xmsg::proto::Meta_Status Meta::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::xmsg::proto::Meta_Status>(_impl_.status_);
}
inline void Meta::_internal_set_status(::xmsg::proto::Meta_Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::xmsg::proto::Meta_Status_internal_data_));
                                          _impl_.status_ = value;
}

// optional sfixed32 severityId = 5;
inline bool Meta::has_severityid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void Meta::clear_severityid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.severityid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline ::int32_t Meta::severityid() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.severityId)
  return _internal_severityid();
}
inline void Meta::set_severityid(::int32_t value) {
  _internal_set_severityid(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.severityId)
}
inline ::int32_t Meta::_internal_severityid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.severityid_;
}
inline void Meta::_internal_set_severityid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.severityid_ = value;
}

// optional string sender = 6;
inline bool Meta::has_sender() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Meta::clear_sender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sender_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::std::string& Meta::sender() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.sender)
  return _internal_sender();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_sender(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.sender_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.sender)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_sender()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_sender();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.sender)
  return _s;
}
inline const ::std::string& Meta::_internal_sender() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sender_.Get();
}
inline void Meta::_internal_set_sender(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.sender_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_sender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.sender_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_sender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.sender)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.sender_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sender_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_sender(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.sender_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sender_.IsDefault()) {
    _impl_.sender_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.sender)
}

// optional string senderState = 7;
inline bool Meta::has_senderstate() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Meta::clear_senderstate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.senderstate_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::std::string& Meta::senderstate() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.senderState)
  return _internal_senderstate();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_senderstate(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.senderstate_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.senderState)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_senderstate()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_senderstate();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.senderState)
  return _s;
}
inline const ::std::string& Meta::_internal_senderstate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.senderstate_.Get();
}
inline void Meta::_internal_set_senderstate(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.senderstate_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_senderstate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.senderstate_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_senderstate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.senderState)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.senderstate_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.senderstate_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_senderstate(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.senderstate_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.senderstate_.IsDefault()) {
    _impl_.senderstate_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.senderState)
}

// optional fixed32 communicationId = 8;
inline bool Meta::has_communicationid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void Meta::clear_communicationid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.communicationid_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline ::uint32_t Meta::communicationid() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.communicationId)
  return _internal_communicationid();
}
inline void Meta::set_communicationid(::uint32_t value) {
  _internal_set_communicationid(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.communicationId)
}
inline ::uint32_t Meta::_internal_communicationid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.communicationid_;
}
inline void Meta::_internal_set_communicationid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.communicationid_ = value;
}

// optional string composition = 10;
inline bool Meta::has_composition() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Meta::clear_composition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.composition_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const ::std::string& Meta::composition() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.composition)
  return _internal_composition();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_composition(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.composition_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.composition)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_composition()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_composition();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.composition)
  return _s;
}
inline const ::std::string& Meta::_internal_composition() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.composition_.Get();
}
inline void Meta::_internal_set_composition(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.composition_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_composition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.composition_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_composition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.composition)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.composition_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.composition_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_composition(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.composition_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.composition_.IsDefault()) {
    _impl_.composition_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.composition)
}

// optional sfixed64 executionTime = 11;
inline bool Meta::has_executiontime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void Meta::clear_executiontime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.executiontime_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline ::int64_t Meta::executiontime() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.executionTime)
  return _internal_executiontime();
}
inline void Meta::set_executiontime(::int64_t value) {
  _internal_set_executiontime(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.executionTime)
}
inline ::int64_t Meta::_internal_executiontime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.executiontime_;
}
inline void Meta::_internal_set_executiontime(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.executiontime_ = value;
}

// optional .xmsg.proto.Meta.ControlAction action = 12;
inline bool Meta::has_action() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void Meta::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline ::xmsg::proto::Meta_ControlAction Meta::action() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.action)
  return _internal_action();
}
inline void Meta::set_action(::xmsg::proto::Meta_ControlAction value) {
  _internal_set_action(value);
  _impl_._has_bits_[0] |= 0x00001000u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.action)
}
inline ::xmsg::proto::Meta_ControlAction Meta::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::xmsg::proto::Meta_ControlAction>(_impl_.action_);
}
inline void Meta::_internal_set_action(::xmsg::proto::Meta_ControlAction value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::xmsg::proto::Meta_ControlAction_internal_data_));
                                          _impl_.action_ = value;
}

// optional .xmsg.proto.Meta.SubControlAction control = 13;
inline bool Meta::has_control() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline void Meta::clear_control() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.control_ = 0;
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline ::xmsg::proto::Meta_SubControlAction Meta::control() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.control)
  return _internal_control();
}
inline void Meta::set_control(::xmsg::proto::Meta_SubControlAction value) {
  _internal_set_control(value);
  _impl_._has_bits_[0] |= 0x00002000u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.control)
}
inline ::xmsg::proto::Meta_SubControlAction Meta::_internal_control() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::xmsg::proto::Meta_SubControlAction>(_impl_.control_);
}
inline void Meta::_internal_set_control(::xmsg::proto::Meta_SubControlAction value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::xmsg::proto::Meta_SubControlAction_internal_data_));
                                          _impl_.control_ = value;
}

// required string dataType = 14;
inline bool Meta::has_datatype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void Meta::clear_datatype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.datatype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const ::std::string& Meta::datatype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.dataType)
  return _internal_datatype();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_datatype(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.datatype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.dataType)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_datatype()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_datatype();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.dataType)
  return _s;
}
inline const ::std::string& Meta::_internal_datatype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.datatype_.Get();
}
inline void Meta::_internal_set_datatype(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.datatype_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_datatype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.datatype_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_datatype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.dataType)
  if ((_impl_._has_bits_[0] & 0x00000040u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* released = _impl_.datatype_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.datatype_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_datatype(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.datatype_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.datatype_.IsDefault()) {
    _impl_.datatype_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.dataType)
}

// optional string datTypeDescription = 15;
inline bool Meta::has_dattypedescription() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void Meta::clear_dattypedescription() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dattypedescription_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const ::std::string& Meta::dattypedescription() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.datTypeDescription)
  return _internal_dattypedescription();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_dattypedescription(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.dattypedescription_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.datTypeDescription)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_dattypedescription()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_dattypedescription();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.datTypeDescription)
  return _s;
}
inline const ::std::string& Meta::_internal_dattypedescription() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dattypedescription_.Get();
}
inline void Meta::_internal_set_dattypedescription(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.dattypedescription_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_dattypedescription() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  return _impl_.dattypedescription_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_dattypedescription() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.datTypeDescription)
  if ((_impl_._has_bits_[0] & 0x00000080u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080u;
  auto* released = _impl_.dattypedescription_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dattypedescription_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_dattypedescription(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.dattypedescription_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dattypedescription_.IsDefault()) {
    _impl_.dattypedescription_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.datTypeDescription)
}

// optional string replyTo = 16;
inline bool Meta::has_replyto() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void Meta::clear_replyto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.replyto_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const ::std::string& Meta::replyto() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.replyTo)
  return _internal_replyto();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Meta::set_replyto(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.replyto_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.replyTo)
}
inline ::std::string* PROTOBUF_NONNULL Meta::mutable_replyto()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_replyto();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Meta.replyTo)
  return _s;
}
inline const ::std::string& Meta::_internal_replyto() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.replyto_.Get();
}
inline void Meta::_internal_set_replyto(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.replyto_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Meta::_internal_mutable_replyto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  return _impl_.replyto_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Meta::release_replyto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Meta.replyTo)
  if ((_impl_._has_bits_[0] & 0x00000100u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000100u;
  auto* released = _impl_.replyto_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.replyto_.Set("", GetArena());
  }
  return released;
}
inline void Meta::set_allocated_replyto(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.replyto_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.replyto_.IsDefault()) {
    _impl_.replyto_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Meta.replyTo)
}

// optional .xmsg.proto.Meta.Endian byteOrder = 17;
inline bool Meta::has_byteorder() const {
  bool value = (_impl_._has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline void Meta::clear_byteorder() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.byteorder_ = 1;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline ::xmsg::proto::Meta_Endian Meta::byteorder() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Meta.byteOrder)
  return _internal_byteorder();
}
inline void Meta::set_byteorder(::xmsg::proto::Meta_Endian value) {
  _internal_set_byteorder(value);
  _impl_._has_bits_[0] |= 0x00008000u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Meta.byteOrder)
}
inline ::xmsg::proto::Meta_Endian Meta::_internal_byteorder() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::xmsg::proto::Meta_Endian>(_impl_.byteorder_);
}
inline void Meta::_internal_set_byteorder(::xmsg::proto::Meta_Endian value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::xmsg::proto::Meta_Endian_internal_data_));
                                          _impl_.byteorder_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace xmsg


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::xmsg::proto::Meta_Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::xmsg::proto::Meta_Status>() {
  return ::xmsg::proto::Meta_Status_descriptor();
}
template <>
struct is_proto_enum<::xmsg::proto::Meta_Endian> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::xmsg::proto::Meta_Endian>() {
  return ::xmsg::proto::Meta_Endian_descriptor();
}
template <>
struct is_proto_enum<::xmsg::proto::Meta_ControlAction> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::xmsg::proto::Meta_ControlAction>() {
  return ::xmsg::proto::Meta_ControlAction_descriptor();
}
template <>
struct is_proto_enum<::xmsg::proto::Meta_SubControlAction> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::xmsg::proto::Meta_SubControlAction>() {
  return ::xmsg::proto::Meta_SubControlAction_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // meta_2eproto_2epb_2eh
