// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registration.proto
// Protobuf C++ Version: 6.31.1

#ifndef registration_2eproto_2epb_2eh
#define registration_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_registration_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_registration_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_registration_2eproto;
}  // extern "C"
namespace xmsg {
namespace proto {
enum Registration_OwnerType : int;
extern const uint32_t Registration_OwnerType_internal_data_[];
class Registration;
struct RegistrationDefaultTypeInternal;
extern RegistrationDefaultTypeInternal _Registration_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Registration_class_data_;
}  // namespace proto
}  // namespace xmsg
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::xmsg::proto::Registration_OwnerType_internal_data_>
    internal::EnumTraitsImpl::value<::xmsg::proto::Registration_OwnerType>;
}  // namespace protobuf
}  // namespace google

namespace xmsg {
namespace proto {
enum Registration_OwnerType : int {
  Registration_OwnerType_PUBLISHER = 1,
  Registration_OwnerType_SUBSCRIBER = 2,
};

extern const uint32_t Registration_OwnerType_internal_data_[];
inline constexpr Registration_OwnerType Registration_OwnerType_OwnerType_MIN =
    static_cast<Registration_OwnerType>(1);
inline constexpr Registration_OwnerType Registration_OwnerType_OwnerType_MAX =
    static_cast<Registration_OwnerType>(2);
inline bool Registration_OwnerType_IsValid(int value) {
  return 1 <= value && value <= 2;
}
inline constexpr int Registration_OwnerType_OwnerType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Registration_OwnerType_descriptor();
template <typename T>
const ::std::string& Registration_OwnerType_Name(T value) {
  static_assert(::std::is_same<T, Registration_OwnerType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to OwnerType_Name().");
  return Registration_OwnerType_Name(static_cast<Registration_OwnerType>(value));
}
template <>
inline const ::std::string& Registration_OwnerType_Name(Registration_OwnerType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Registration_OwnerType_descriptor, 1, 2>(
      static_cast<int>(value));
}
inline bool Registration_OwnerType_Parse(
    ::absl::string_view name, Registration_OwnerType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Registration_OwnerType>(Registration_OwnerType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Registration final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:xmsg.proto.Registration) */ {
 public:
  inline Registration() : Registration(nullptr) {}
  ~Registration() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Registration* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Registration));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Registration(::google::protobuf::internal::ConstantInitialized);

  inline Registration(const Registration& from) : Registration(nullptr, from) {}
  inline Registration(Registration&& from) noexcept
      : Registration(nullptr, ::std::move(from)) {}
  inline Registration& operator=(const Registration& from) {
    CopyFrom(from);
    return *this;
  }
  inline Registration& operator=(Registration&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Registration& default_instance() {
    return *reinterpret_cast<const Registration*>(
        &_Registration_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Registration& a, Registration& b) { a.Swap(&b); }
  inline void Swap(Registration* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Registration* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Registration* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Registration>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Registration& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Registration& from) { Registration::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Registration* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "xmsg.proto.Registration"; }

 protected:
  explicit Registration(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Registration(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Registration& from);
  Registration(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Registration&& from) noexcept
      : Registration(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using OwnerType = Registration_OwnerType;
  static constexpr OwnerType PUBLISHER = Registration_OwnerType_PUBLISHER;
  static constexpr OwnerType SUBSCRIBER = Registration_OwnerType_SUBSCRIBER;
  static inline bool OwnerType_IsValid(int value) {
    return Registration_OwnerType_IsValid(value);
  }
  static constexpr OwnerType OwnerType_MIN = Registration_OwnerType_OwnerType_MIN;
  static constexpr OwnerType OwnerType_MAX = Registration_OwnerType_OwnerType_MAX;
  static constexpr int OwnerType_ARRAYSIZE = Registration_OwnerType_OwnerType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL OwnerType_descriptor() {
    return Registration_OwnerType_descriptor();
  }
  template <typename T>
  static inline const ::std::string& OwnerType_Name(T value) {
    return Registration_OwnerType_Name(value);
  }
  static inline bool OwnerType_Parse(
      ::absl::string_view name, OwnerType* PROTOBUF_NONNULL value) {
    return Registration_OwnerType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kDescriptionFieldNumber = 2,
    kHostFieldNumber = 3,
    kDomainFieldNumber = 5,
    kSubjectFieldNumber = 6,
    kTypeFieldNumber = 7,
    kPortFieldNumber = 4,
    kOwnerTypeFieldNumber = 8,
  };
  // required string name = 1;
  bool has_name() const;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // optional string description = 2 [default = "undefined"];
  bool has_description() const;
  void clear_description() ;
  const ::std::string& description() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_description(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_description();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_description();
  void set_allocated_description(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_description() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_description(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_description();

  public:
  // required string host = 3;
  bool has_host() const;
  void clear_host() ;
  const ::std::string& host() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_host(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_host();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_host();
  void set_allocated_host(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_host() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_host(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_host();

  public:
  // required string domain = 5;
  bool has_domain() const;
  void clear_domain() ;
  const ::std::string& domain() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_domain(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_domain();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_domain();
  void set_allocated_domain(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_domain() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_domain(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_domain();

  public:
  // optional string subject = 6 [default = "undefined"];
  bool has_subject() const;
  void clear_subject() ;
  const ::std::string& subject() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_subject(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_subject();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_subject();
  void set_allocated_subject(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_subject() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_subject(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_subject();

  public:
  // optional string type = 7 [default = "undefined"];
  bool has_type() const;
  void clear_type() ;
  const ::std::string& type() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_type();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_type();
  void set_allocated_type(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_type() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_type(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_type();

  public:
  // required sfixed32 port = 4;
  bool has_port() const;
  void clear_port() ;
  ::int32_t port() const;
  void set_port(::int32_t value);

  private:
  ::int32_t _internal_port() const;
  void _internal_set_port(::int32_t value);

  public:
  // optional .xmsg.proto.Registration.OwnerType ownerType = 8;
  bool has_ownertype() const;
  void clear_ownertype() ;
  ::xmsg::proto::Registration_OwnerType ownertype() const;
  void set_ownertype(::xmsg::proto::Registration_OwnerType value);

  private:
  ::xmsg::proto::Registration_OwnerType _internal_ownertype() const;
  void _internal_set_ownertype(::xmsg::proto::Registration_OwnerType value);

  public:
  // @@protoc_insertion_point(class_scope:xmsg.proto.Registration)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   1, 76,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Registration& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    static const ::google::protobuf::internal::LazyString _i_give_permission_to_break_this_code_default_description_;
    ::google::protobuf::internal::ArenaStringPtr description_;
    ::google::protobuf::internal::ArenaStringPtr host_;
    ::google::protobuf::internal::ArenaStringPtr domain_;
    static const ::google::protobuf::internal::LazyString _i_give_permission_to_break_this_code_default_subject_;
    ::google::protobuf::internal::ArenaStringPtr subject_;
    static const ::google::protobuf::internal::LazyString _i_give_permission_to_break_this_code_default_type_;
    ::google::protobuf::internal::ArenaStringPtr type_;
    ::int32_t port_;
    int ownertype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_registration_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Registration_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Registration

// required string name = 1;
inline bool Registration::has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Registration::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Registration::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Registration::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.name)
}
inline ::std::string* PROTOBUF_NONNULL Registration::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Registration.name)
  return _s;
}
inline const ::std::string& Registration::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Registration::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Registration::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Registration::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Registration.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void Registration::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Registration.name)
}

// optional string description = 2 [default = "undefined"];
inline bool Registration::has_description() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Registration::clear_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.description_.ClearToDefault(::xmsg::proto::Registration::Impl_::_i_give_permission_to_break_this_code_default_description_, GetArena());
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& Registration::description() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.description)
  if (_impl_.description_.IsDefault()) {
    return Impl_::_i_give_permission_to_break_this_code_default_description_.get();
  }
  return _internal_description();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Registration::set_description(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.description_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.description)
}
inline ::std::string* PROTOBUF_NONNULL Registration::mutable_description()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Registration.description)
  return _s;
}
inline const ::std::string& Registration::_internal_description() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.description_.Get();
}
inline void Registration::_internal_set_description(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.description_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Registration::_internal_mutable_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.description_.Mutable(::xmsg::proto::Registration::Impl_::_i_give_permission_to_break_this_code_default_description_, GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Registration::release_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Registration.description)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  return _impl_.description_.Release();
}
inline void Registration::set_allocated_description(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.description_.SetAllocated(value, GetArena());
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Registration.description)
}

// required string host = 3;
inline bool Registration::has_host() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Registration::clear_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& Registration::host() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.host)
  return _internal_host();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Registration::set_host(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.host_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.host)
}
inline ::std::string* PROTOBUF_NONNULL Registration::mutable_host()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Registration.host)
  return _s;
}
inline const ::std::string& Registration::_internal_host() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.host_.Get();
}
inline void Registration::_internal_set_host(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.host_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Registration::_internal_mutable_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.host_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Registration::release_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Registration.host)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.host_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.host_.Set("", GetArena());
  }
  return released;
}
inline void Registration::set_allocated_host(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.host_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Registration.host)
}

// required sfixed32 port = 4;
inline bool Registration::has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void Registration::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t Registration::port() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.port)
  return _internal_port();
}
inline void Registration::set_port(::int32_t value) {
  _internal_set_port(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.port)
}
inline ::int32_t Registration::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void Registration::_internal_set_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// required string domain = 5;
inline bool Registration::has_domain() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Registration::clear_domain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.domain_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::std::string& Registration::domain() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.domain)
  return _internal_domain();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Registration::set_domain(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.domain_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.domain)
}
inline ::std::string* PROTOBUF_NONNULL Registration::mutable_domain()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_domain();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Registration.domain)
  return _s;
}
inline const ::std::string& Registration::_internal_domain() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.domain_.Get();
}
inline void Registration::_internal_set_domain(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.domain_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Registration::_internal_mutable_domain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.domain_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Registration::release_domain() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Registration.domain)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.domain_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.domain_.Set("", GetArena());
  }
  return released;
}
inline void Registration::set_allocated_domain(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.domain_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.domain_.IsDefault()) {
    _impl_.domain_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Registration.domain)
}

// optional string subject = 6 [default = "undefined"];
inline bool Registration::has_subject() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Registration::clear_subject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subject_.ClearToDefault(::xmsg::proto::Registration::Impl_::_i_give_permission_to_break_this_code_default_subject_, GetArena());
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::std::string& Registration::subject() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.subject)
  if (_impl_.subject_.IsDefault()) {
    return Impl_::_i_give_permission_to_break_this_code_default_subject_.get();
  }
  return _internal_subject();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Registration::set_subject(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.subject_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.subject)
}
inline ::std::string* PROTOBUF_NONNULL Registration::mutable_subject()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_subject();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Registration.subject)
  return _s;
}
inline const ::std::string& Registration::_internal_subject() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.subject_.Get();
}
inline void Registration::_internal_set_subject(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.subject_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Registration::_internal_mutable_subject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.subject_.Mutable(::xmsg::proto::Registration::Impl_::_i_give_permission_to_break_this_code_default_subject_, GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Registration::release_subject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Registration.subject)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  return _impl_.subject_.Release();
}
inline void Registration::set_allocated_subject(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.subject_.SetAllocated(value, GetArena());
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Registration.subject)
}

// optional string type = 7 [default = "undefined"];
inline bool Registration::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Registration::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.ClearToDefault(::xmsg::proto::Registration::Impl_::_i_give_permission_to_break_this_code_default_type_, GetArena());
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const ::std::string& Registration::type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.type)
  if (_impl_.type_.IsDefault()) {
    return Impl_::_i_give_permission_to_break_this_code_default_type_.get();
  }
  return _internal_type();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Registration::set_type(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.type)
}
inline ::std::string* PROTOBUF_NONNULL Registration::mutable_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:xmsg.proto.Registration.type)
  return _s;
}
inline const ::std::string& Registration::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_.Get();
}
inline void Registration::_internal_set_type(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.type_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Registration::_internal_mutable_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.type_.Mutable(::xmsg::proto::Registration::Impl_::_i_give_permission_to_break_this_code_default_type_, GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Registration::release_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:xmsg.proto.Registration.type)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  return _impl_.type_.Release();
}
inline void Registration::set_allocated_type(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.type_.SetAllocated(value, GetArena());
  // @@protoc_insertion_point(field_set_allocated:xmsg.proto.Registration.type)
}

// optional .xmsg.proto.Registration.OwnerType ownerType = 8;
inline bool Registration::has_ownertype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void Registration::clear_ownertype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ownertype_ = 1;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::xmsg::proto::Registration_OwnerType Registration::ownertype() const {
  // @@protoc_insertion_point(field_get:xmsg.proto.Registration.ownerType)
  return _internal_ownertype();
}
inline void Registration::set_ownertype(::xmsg::proto::Registration_OwnerType value) {
  _internal_set_ownertype(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:xmsg.proto.Registration.ownerType)
}
inline ::xmsg::proto::Registration_OwnerType Registration::_internal_ownertype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::xmsg::proto::Registration_OwnerType>(_impl_.ownertype_);
}
inline void Registration::_internal_set_ownertype(::xmsg::proto::Registration_OwnerType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::xmsg::proto::Registration_OwnerType_internal_data_));
                                          _impl_.ownertype_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace xmsg


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::xmsg::proto::Registration_OwnerType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::xmsg::proto::Registration_OwnerType>() {
  return ::xmsg::proto::Registration_OwnerType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // registration_2eproto_2epb_2eh
